### PR TITLE
Remove genomicsSecretsFile, as secretsFile is now part of GcpOptions

### PR DESCRIPTION
**Pull request by tovanadler**

### CODE REVIEW

**Comment by deflaux** [comment]
@tovanadler This is a nice tidy change!  

Question: is there a similar redundancy for --apiKey?

I was thinking we should update and merge the related docs at the same time to avoid some potential confusion.  (an alternative would be to have use of ``--genomicsSecretsFile`` return a helpful error message).  For more context on why we've got docs in two places, see https://github.com/googlegenomics/dataflow-java/issues/28

If that sounds good to you, can you also please:
  1. delete src/main/scripts/count_reads.sh (now that we have [the cookbook entry] (http://googlegenomics.readthedocs.org/en/latest/use_cases/analyze_reads/count_reads.html))
  1. add the [pre-built jar](https://github.com/googlegenomics/dataflow-java#updating-the-prebuilt-jar)
  1. get the pull request ready for https://github.com/googlegenomics/start-here that `s/genomicsSecretsFile/secretsFile/g` 

There are a few github repos that have code that depends upon this jar, but they won't pick up the change until they bump their dependency version, so we can save those docs updates for that version bump.

**Comment by tovanadler** [comment]
That does sound good and is the second half of the bug that this was based
on and will try to do those two things ASAP.

**Comment by tovanadler** [comment]
Hey Nicole,
Turns out that apiKey is seperate and I don't see that in the general dataflow pipeline. This is the bug I was working on: https://github.com/googlegenomics/dataflow-java/issues/72. I did the other three things that you mentioned. Thank you!

**Comment by pgrosu** [comment]
@tovanadler I think the API key part of the initialization of the DataflowBaseService instance.  Below is a link to more information about this:

https://developers.google.com/resources/api-libraries/documentation/dataflow/v1b3/csharp/latest/classGoogle_1_1Apis_1_1Dataflow_1_1v1b3_1_1DataflowBaseServiceRequest-g.html

~p

**Comment by deflaux** [comment]
@tovanadler  This looks great.  I'm doing a little more testing on my side before merging this.

**Pull request merged**
