### PR TITLE
delete files after use

### PR DESCRIPTION
**Pull request by jean-philippe-martin**
Delete test outputs after the test.

### CODE REVIEW

**Comment by deflaux** [comment]
This looks good.  Merge it when ever you are ready.

Note that there are alternate approaches to creating a temp dir and cleaning up so that it does not need to be done in each individual test.  Failsafe hooks into the pre- and post-integration-test maven phases and some logic can be added there.  Another alternative, though less tidy than making use of the maven phases, is to number all integration tests so that they run in a particular order (e.g., have an setup integration test that starts with "000"  and a teardown that runs in "999").

**Comment by jean-philippe-martin** [comment]
@deflaux true, we could do that. It's a matter of taste I suppose: I like deleting only the specific file created (and have each test use a different file) because (i) unlike the "delete every file in the folder" approach, it's robust to having multiple tests running in parallel and (ii) if we need to inspect the output, having each test output to its own file makes that easier - just delete the corresponding delete. And generally I like to have paired operations near each other, so if each test creates a file I prefer to have it deleted in the same function. But I agree that there are also advantages to the approach of using a dedicated folder and nuking it afterwards.

**Comment by jean-philippe-martin** [comment]
@googlebot, you're slowing us down. Have some coffee!

**Comment by pgrosu** [comment]
@jean-philippe-martin :)

**Comment by jean-philippe-martin** [comment]
merged manually.

**Pull request closed without merging**
