### PR TITLE
Add integration tests using the NA12877_S1 dataset.

### PR DESCRIPTION
**Pull request by jakeakopp**

### CODE REVIEW

**Comment by jakeakopp** [comment]
I "signed" the CLA.

**Comment by iliat** [comment]
Thanks @jakeakopp  !
How long does it take to run over a larger dataset ?
@deflaux - are you ok with this, slightly longer running, test to be invoked with "mvn verify" ?

**Comment by jakeakopp** [comment]
Takes about 15 minutes to run "mvn verify" now.

**Comment by pgrosu** [comment]
@iliat, @jakeakopp  I think Travis' limit is about 25 minutes which @siddharthab tried here:

https://github.com/googlegenomics/api-client-r/issues/38#issuecomment-100074402

Keep in mind that Travis is outside the Google domain so the 4-5 sec overhead per API request - discussed at the following location - also adds up as well:

https://github.com/googlegenomics/utils-java/issues/9

~p

**Comment by deflaux** [comment]
@jakeakopp This code looks good to me.  Nice additional tests!

At some point sooner or later I would imagine we'll want to refactor to put *test helper* code in a separate file and then split the integration test cases into the "fast ones" we want to run often and the "slow ones" we want to run less often.  With the failsafe plugin you can specify a more constrained file pattern for the integration tests to run by default (e.g., the fast ones).

@iliat  and @jean-philippe-martin What we want to avoid is people getting in the habit of running `mvn install -DskipITs` nearly all the time so please chime in if you think this refactoring should happen sooner.

**Comment by jean-philippe-martin** [comment]
How urgent that is depends on whether we have many fast integration tests.
So long as they are almost all slow, I'm fine with -DskipIT as our idiom
for "skip slow tests".

**Comment by pgrosu** [comment]
@deflaux Well...there is a way though to still force the tests to run, even if users would include `mvn install -DskipITs` :)

**Pull request merged**
