### PR TITLE
Bump utils-java.

### PR DESCRIPTION
**Pull request by deflaux**

### CODE REVIEW

**Comment by pgrosu** [comment]
Maybe `google-api-services-genomics` might also need to be updated to `v1-rev59-1.21.0` from `v1beta2-rev87-1.20.0` - at the following line:

https://github.com/googlegenomics/dataflow-java/blob/master/pom.xml#L117

~p

**Comment by calbach** [comment]
LGTM

**Comment by deflaux** [comment]
@pgrosu We have an example in here that uses the Annotations API which is not in v1 yet, so we're leaving it at v1beta2 for now.

**Comment by pgrosu** [comment]
Hi Nicole,

That sounds reasonable, but then why not bump it to the latest `v1beta2` which is `v1beta2-rev99-1.21.0`?

Paul

**Pull request merged**
