### PR TITLE
Update to v1 of genomics API.

### PR DESCRIPTION
**Pull request by deflaux**
Travis CI will be happy when the new build of utils-java is available.

### CODE REVIEW

**Comment by pgrosu** [comment]
@deflaux There seem to be some errors :(

```
... Failure to find com.google.cloud.genomics:google-genomics-utils:jar:v1-0.1 in http://repo.maven.apache.org/maven2 was cached in the local repository...
```

**Comment by melissachang** [comment]
LGTM, assuming you fix the error Paul pointed out.

**Comment by deflaux** [comment]
@pgrosu Thanks for the comment! Travis CI will be happy when the new build of utils-java is available.  Its not in maven central yet.

**Comment by pgrosu** [comment]
@deflaux Ah, got it - thanks :)

~p

**Comment by deflaux** [comment]
Travis CI is green now.

**Comment by pgrosu** [comment]
Yay 😄

**Pull request merged**
