### PR TITLE
Enforce window within merge logic.

### PR DESCRIPTION
**Pull request by deflaux**
Corresponding changes per https://github.com/googlegenomics/utils-java/pull/95

Sending this to a branch for now.  Travis CI will turn green when the next version of utils-java is released.

### CODE REVIEW

**Comment by dionloy** [comment]
LGTM

(I assume the build breakage is due to utils-java version not ready yet?)

**Comment by deflaux** [comment]
Yes, that's right.  This won't get merged to master until Travis CI is green.

**Comment by pgrosu** [comment]
Hi Nicole,

So just to be sure, after reading through the utils-java and dataflow-java code-bases, how are you merging non-variant segments if the calls for IBS similarity calculation is focused at coordinate-based snp comparisons?  Basically how would the non-variant segments without additional alternate alleles besides `<NON_REF>` provide any significant information without diluting the IBS score, which is reflected in the scores in the [1000 Genomes analysis for chromosome 22](https://github.com/googlegenomics/dataflow-java/blob/master/results/ibs/1000Genomes-chr22/analyze-ibs-data.md).

If you are getting the call-list from [MergeNonVariantSegmentsWithSnps.java](https://github.com/googlegenomics/utils-java/blob/cdf02e8671198ca7638059db81983cadd526497e/src/main/java/com/google/cloud/genomics/utils/grpc/MergeNonVariantSegmentsWithSnps.java#L59) via `updatedRecord.addAllCalls(blockRecord.getCallsList());` to then perform `addAllCalls(
java.lang.Iterable<? extends com.google.genomics.v1.VariantCall> values)` from [v1/Variant.java](https://github.com/googlegenomics/utils-java/blob/cdf02e8671198ca7638059db81983cadd526497e/src/main/java/com/google/genomics/v1/Variant.java#L2338-2350), what would be the calls used for comparison from a non-variant segment?

Thanks,
~p

**Comment by deflaux** [comment]
Hi Paul!  There are two methods so far for calculating IBS:
* https://github.com/googlegenomics/dataflow-java/blob/master/src/main/java/com/google/cloud/genomics/dataflow/functions/ibs/SharedAllelesRatioCalculator.java
* https://github.com/googlegenomics/dataflow-java/blob/master/src/main/java/com/google/cloud/genomics/dataflow/functions/ibs/SharedMinorAllelesCalculator.java  <-- this one determines the "minor allele" and therefore needs to take into account reference calls

**Comment by pgrosu** [comment]
Hi Nicole!

Wow, not to worry but there are some things that probably we should work through carefully on this one.  So for IBS it probably would be good to go by the actual calls - as well as the genotypes - since we're working on the cloud and folks might attempt to use combined cohorts from separate datasets.  Variants across cohorts might not be matching in alternates.  Another thing is that to match by `CallSetName` is taking some big assumptions in how people will use IBS:

```
 public double similarity(VariantCall call1, VariantCall call2) {
    if (call1.getCallSetName().equals(call2.getCallSetName())) {
      return 1.0;
    }
...
```

If reference has the most counts, then if you are performing `any` on greater than 1, then you are missing the difference between 1 and 2 which can exist for 1/2 and other scenarios:

```
private boolean hasMinorAllele(VariantCall call) {
    return Iterables.any(call.getGenotypeList(), new Predicate<Integer>() {

      @Override
      public boolean apply(Integer genotype) {
        if (isReferenceMajor) {
          return genotype > 0;
```

Please don't take this the wrong way, but I think the minor allele comparison will require a bit more thorough investigation, since some bioinformatician will download the code and might assume some evaluation criteria, when the code could be performing something different.  At the very least the evaluation criteria should probably be detailed in the documentation, so that no surprises arise.

~p

**Comment by deflaux** [comment]
@pgrosu I deleted your comment because it contained code. Due to [the rules of this project](https://github.com/googlegenomics/dataflow-java/blob/master/CONTRIBUTING.rst), you must sign the CLA or refrain from including code in any comments.  We really value your participation and help. I know you put a lot of effort into your comments, and so it wastes your effort when we must delete them. Please help us and sign the CLA or stop including code in your comments.

**Comment by pgrosu** [comment]
@deflaux It was all your code that is part of this repository, and I was not contributing.  I just wanted to make you aware there are issues with your approach of calculating IBS, and that the calculation is not always specific to the calls.  I thought that GoogleGenomics wanted to be as scientific and mathematically correct about contributed code.  Isn't that the goal?

**Pull request merged**
