### PR TITLE
test_count_reads

### PR DESCRIPTION
**Pull request by jean-philippe-martin**
A first shot at an integration test that we can run to make sure everything still works as it should. For now it just runs the CountReads sample, but eventually we should test all pipelines this way.

I tried Maven integration (with the integration-test goal) but that didn't work for me. I need to level up before trying again.

### CODE REVIEW

**Comment by dionloy** [comment]
Nicole, could you take a look at this? I think it's a good idea in general, but are there any better tools for us to utilize for integration tests other than the shell script? (also any suggested improvements on the environment variable file?).

**Comment by deflaux** [comment]
For integration tests for Java code, the maven [failsafe plugin](http://maven.apache.org/surefire/maven-failsafe-plugin/) is a good approach.  Perhaps something like this:

1. Update [.travis.yml](https://github.com/googlegenomics/dataflow-java/blob/master/.travis.yml) to run the failsafe target in addition to the current surefire target for unit tests.

1. We set a few environment variables in [travis-ci](http://docs.travis-ci.com/):

   * API_KEY  (instead of client_secrets)
   * PROJECT (for dataflow)
   * BUCKET/PREFIX (destination bucket for staging and pipeline output)

  If someone else forked the repo, all they would need to do is set these three values in their own travis-ci configuration and the integration tests via travis should work for them.  For local development, we just set these three values in `.m2/settings.xml` to our own individual values (especially BUCKET/PREFIX) so that we don't clobber each other's test results.

1. In the integration test setup phase we grab these three values from the environment.

1. For each pipeline, we have the three environment variables and the other parameters are hardcoded to public data and programmatically passed to PipelineOptions.  We kick off the pipeline in a blocking runner.  When complete, the integration test grabs the results from GCS and compares it to the expected result.

1. In the integration test teardown phase we clean up integration test results in GCS.

The [tests](https://github.com/googlegenomics/api-client-r/blob/master/tests/testthat/test-getVariants.R) for api-client-r are integration tests, but they are a little less complicated because they create no state as the output of test results.

**Comment by jean-philippe-martin** [comment]
Yes, but... this isn't java code. It's a shell script.

I'm doing it this way because Pipeline.run does not return an error if the
pipeline fails. So the java program itself has no idea whether it failed.
Pipeline.run instead prints diagnostic codes to standard out. The script
greps that and makes sure that the output's there.

Are you suggesting we write a Java program to grab the results from GCS and
compare them against known good results, instead of the equivalent 2-line
shell script? Sure, we could do this but I don't understand the bash hate.
Bash is available on every major platform (Linux, Mac, Windows).

Do you really want to run those at every single checkin? It'll slow things
down significantly (remember that each cloud Dataflow job currently has a
60s overhead. The ReadCount sample has 2 code paths, so we run on the cloud
twice). I was picturing a test that we run before making a release.

Cheers,
JP

**Comment by dionloy** [comment]
bash vs Java it's less about the language itself but the framework around
it to support what we would like to do. Since there is Maven support for
something more structured, let's go with that.

Let's see how things go wrt to flakiness or commit time in practice. If it
really gets in the way we can remove from automation and make it a manual
step.

**Comment by pgrosu** [comment]
Might not sharing the API_KEY publicly be somewhat dangerous?

**Comment by deflaux** [comment]
@pgrosu The API_KEY won't be public.  It will be stored in the Travis-CI settings.  (same as for api-client-r)

@jean-philippe-martin I agree with you that we definitely want to run them before a release.  It would be good to also have the integration tests run for pull requests to googlegenomics/dataflow-java
  * We all do work in our own forks so those individual commits won't trigger the integration tests unless we each explicitly setup Travis-CI this way for our own forks.  But if it were setup that way, just add [[ci skip]](http://docs.travis-ci.com/user/how-to-skip-a-build/) to commits that don't merit a Travis build.
  * The unit and integration tests can [be run in parallel](http://docs.travis-ci.com/user/speeding-up-the-build/) so that the feedback is returned sooner for the unit tests.

But as @dionloy says, we can switch it back to a manual process if integration tests become too cumbersome for the pulls.

**Comment by pgrosu** [comment]
Great!  Thanks Nicole :)

**Pull request closed without merging**
