### PR TITLE
Refactor streamers to utils-java for reuse by spark.

### PR DESCRIPTION
**Pull request by deflaux**
Fixes 
* https://github.com/googlegenomics/utils-java/issues/34
* https://github.com/googlegenomics/utils-java/issues/35
* https://github.com/googlegenomics/dataflow-java/issues/122

Goes along with https://github.com/googlegenomics/utils-java/pull/49

### CODE REVIEW

**Comment by deflaux** [comment]
I tested this via:
* utils-java/refactor-part1: mvn install
* dataflow-java/refactor-redo: mvn verify

And noticed that everything passed except the one integration test for streaming dataflow running on cloud. It _was_ using the default credential and the auth refactor took that away.  I'll add a fix for that.

**Comment by deflaux** [comment]
@jean-philippe-martin `mvn verify` now passes due to https://github.com/googlegenomics/utils-java/pull/52

**Comment by jean-philippe-martin** [comment]
yay!

**Comment by jean-philippe-martin** [comment]
yes, that was a "looks good, you can merge" yay. I was about to clarify but I see you understood me :)

**Pull request merged**
