### PR TITLE
add failsafe plugin

### PR DESCRIPTION
**Pull request by jean-philippe-martin**
use "mvn verify" to run the integration tests.

### CODE REVIEW

**Comment by jean-philippe-martin** [comment]
Hold on, the test just finished on my machine, looks like it didn't work! I'll investigate tomorrow.

**Comment by jean-philippe-martin** [comment]
When run from the IDE, everything works. When run from the command line, registerGenomicsCoders fails to register anything, and then the pipeline predictably fails.

The log looks like this:

INFO: Registering coders for genomics classes
May 07, 2015 5:37:49 PM org.reflections.vfs.Vfs fromURL
WARNING: could not create Dir using commons_vfs2 from url file:/usr/lib/x86_64-linux-gnu/jni/libatk-wrapper.so.0.0.18. skipping.
(... stack trace. No mention of any coder being registered)
INFO: Reflections took 13 ms to scan 8 urls, producing 0 keys and 0 values

**Comment by deflaux** [comment]
Note that the current coder stuff needs to go away in favor of  [registry.setFallbackCoderProvider](https://cloud.google.com/dataflow/java-sdk/JavaDoc/com/google/cloud/dataflow/sdk/coders/CoderRegistry#setFallbackCoderProvider(com.google.cloud.dataflow.sdk.coders.CoderProvider)) (see the [code and tests](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/search?utf8=%E2%9C%93&q=setFallbackCoderProvider)) per https://github.com/googlegenomics/dataflow-java/issues/60

**Comment by pgrosu** [comment]
Hi JP,

Not sure why you are getting the error, but it works for me from the command line, as shown below based on the code from this PR.  Could you provide the exact steps you ran at the command line, that caused you to get an error?  Also could you provide the complete error as well?  Probably adding Nicole's recommendation first before retesting will simplify our troubleshooting steps :)

```
$ wget https://github.com/googlegenomics/dataflow-java/archive/012854e76998e4d0cad957d7f1a6d9b36fb635ea.zip
$ unzip 012854e76998e4d0cad957d7f1a6d9b36fb635ea.zip
$ cd dataflow-java-012854e76998e4d0cad957d7f1a6d9b36fb635ea
$ cp ../../dataflow-java/client_secrets.json .
$ mvn compile
$ mvn bundle:bundle
$
$ vi src/main/java/com/google/cloud/genomics/dataflow/utils/GenomicsDatasetOptions.java
$
$ # The above was perform the fix so it saves locally
$
$ java -cp target/*.jar com.google.cloud.genomics.dataflow.pipelines.VariantSimilarity --genomicsSecretsFile=client_secrets.json --project=<removed> --output=outnew.txt --numWorkers=1

May 07, 2015 11:17:27 PM com.google.cloud.genomics.dataflow.utils.GenomicsDatasetOptions$Methods getVariantRequests
INFO: Adding request with 17 41196311 to 41277499
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coders for genomics classes
May 07, 2015 11:17:28 PM org.reflections.Reflections scan
INFO: Reflections took 244 ms to scan 10 urls, producing 1 keys and 77 values
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for InterleavedFastqSource
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for VariantSet
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ListCoverageBucketsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchCallSetsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchReadsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for BatchAnnotationsResponseEntryStatus
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ExperimentalCreateJobRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchVariantsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for Metadata
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ListBasesResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for JobRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ReferenceSet
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchReadsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ExportVariantSetRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for CallReadGroupSetsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for Transcript
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for Reference
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for AlignReadGroupSetsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for QueryRange
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchJobsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for CigarUnit
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for Annotation
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ImportReadGroupSetsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ExternalId
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ExperimentalCreateJobResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchAnnotationsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for LinearAlignment
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ExportReadGroupSetsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchCallSetsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchReferencesResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for PairedFastqSource
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchAnnotationSetsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for Call
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for CoverageBucket
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchReferenceSetsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for TranscriptExon
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for CallSet
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for Dataset
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ExportReadGroupSetsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for FastqMetadata
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for AnnotationSet
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ReadGroupSet
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchVariantsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for BatchAnnotationsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ReadGroupExperiment
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchReadGroupSetsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ListDatasetsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for Read
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ReadGroup
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for VariantAnnotationCondition
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for RangePosition
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for TranscriptCodingSequence
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for Variant
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ReferenceBound
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ImportVariantsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for Position
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for VariantAnnotation
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for BatchAnnotationsResponseEntry
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchAnnotationSetsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ExportVariantSetResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for Job
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for AlignReadGroupSetsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ImportVariantsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchJobsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchVariantSetsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchReferenceSetsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for MergeVariantsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchVariantSetsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchReferencesRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for CallReadGroupSetsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for Range
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchReadGroupSetsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for Int32Value
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for SearchAnnotationsRequest
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ReadGroupProgram
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for ImportReadGroupSetsResponse
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.utils.DataflowWorkarounds registerGenomicsCoders
INFO: Registering coder for BatchCreateAnnotationsRequest
May 07, 2015 11:17:28 PM com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner run
INFO: Executing pipeline using the DirectPipelineRunner.
May 07, 2015 11:17:28 PM com.google.cloud.genomics.dataflow.readers.VariantReader processApiCall
INFO: Starting Variants read loop: {"end":"41277499","referenceName":"17","start":"41196311","variantSetIds":["10473108253681171589"]}
May 07, 2015 11:19:23 PM com.google.cloud.genomics.dataflow.readers.VariantReader processApiCall
INFO: Read 879 variants at: 17-[41196311, 41277499]
May 07, 2015 11:19:23 PM com.google.cloud.genomics.dataflow.readers.GenomicsApiReader processElement
INFO: ApiReader processed 220 requests (1 server errors and 0 IO exceptions)
May 07, 2015 11:20:31 PM com.google.cloud.dataflow.sdk.coders.CoderRegistry getDefaultCoderFactory
INFO: No Coder registered for class com.google.cloud.genomics.dataflow.functions.PCoAnalysis$GraphResult
May 07, 2015 11:20:31 PM com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner run
INFO: Final aggregator value: user-s1-Genomics API Initialized Request Count:SUM(220)
May 07, 2015 11:20:31 PM com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner run
INFO: Final aggregator value: user-s1-Genomics API Unsuccessful Response Count:SUM(1)
May 07, 2015 11:20:31 PM com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner run
INFO: Final aggregator value: user-s1-Genomics API Item Count:SUM(879)
May 07, 2015 11:20:31 PM com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner run
INFO: Final aggregator value: user-s1-Genomics API IOException Response Count:SUM(0)
May 07, 2015 11:20:31 PM com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner run
INFO: Pipeline execution complete.
[pgrosu@eofe5 dataflow-java-012854e76998e4d0cad957d7f1a6d9b36fb635ea]$
[pgrosu@eofe5 dataflow-java-012854e76998e4d0cad957d7f1a6d9b36fb635ea]$ cat outnew.txt-00000-of-00001
NA19257         -1.09   4.86
HG01072         5.85    -1.65
NA18617         -5.4    -0.44
NA18977         -5.37   -0.47
NA19360         5.01    0.59
HG01521         -5.34   -0.42
HG00472         -5.42   -0.44
HG00130         5.93    -1.6
NA07357         5.83    -1.45
NA19028         -0.92   3.88
...
$
```

Thanks,
~p

**Comment by jean-philippe-martin** [comment]
@pgrosu, to reproduce the error you have to issue this command:

mvn verify

**Comment by jean-philippe-martin** [comment]
yes. That should probably be done first, and then we can investigate why
GenomicsWorkaround doesn't work when invoked via failsafe.

**Comment by pgrosu** [comment]
Thanks @jean-philippe-martin.  By the way on the command-line did you set the following environment variables before running `mvn verify`?

```
export GOOGLE_API_KEY=...
export TEST_OUTPUT_GCS_FOLDER=...
```

~p

**Comment by jean-philippe-martin** [comment]
yes of course.

**Comment by pgrosu** [comment]
Ok, I'll keep digging though I don't have GCS for my account.

**Comment by jean-philippe-martin** [comment]
I expect you should be able to reproduce the problem even without setting
those variables. You should see the GenomicsWorkaround fail to register any
coder. It may then also fail for GCS reasons, but you should be able to
check whether the "Registering coder"... lines appear (if you run the test
from the IDE it works, at least for me, so there you can see what the coder
registration looks like)

**Comment by pgrosu** [comment]
So if I don't set the API key, I get an error like this:

```
CountReadsITCase.voidEnsureEnvVar:34 You must set the GOOGLE_API_KEY environment variable for this test.
```

But after I set `GOOGLE_API_KEY` with my key, and `TEST_OUTPUT_GCS_FOLDER` with a random folder being `gs://test/`, and then I run `mvn -e verify`, I see following error in the files from the `failsafe-reports` folder:

```
$ cat /home/pgrosu/me/gg_dataflow/gg_jean_5-7-fix/dataflow-java-012854e76998e4d0cad957d7f1a6d9b36fb635ea/target/failsafe-reports/com.google.cloud.genomics.dataflow.utils.GCSHelperITCase.txt
-------------------------------------------------------------------------------
Test set: com.google.cloud.genomics.dataflow.utils.GCSHelperITCase
-------------------------------------------------------------------------------
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.527 sec - in com.google.cloud.genomics.dataflow.utils.GCSHelperITCase
$
$
$ cat /home/pgrosu/me/gg_dataflow/gg_jean_5-7-fix/dataflow-java-012854e76998e4d0cad957d7f1a6d9b36fb635ea/target/failsafe-reports/com.google.cloud.genomics.dataflow.pipelines.CountReadsITCase.txt
-------------------------------------------------------------------------------
Test set: com.google.cloud.genomics.dataflow.pipelines.CountReadsITCase
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.251 sec <<< FAILURE! - in com.google.cloud.genomics.dataflow.pipelines.CountReadsITCase
testLocal(com.google.cloud.genomics.dataflow.pipelines.CountReadsITCase)  Time elapsed: 4.251 sec  <<< ERROR!
java.lang.IllegalStateException: unable to infer a default Coder for Read.out [PCollection]; either register a default Coder for its element type, or use setCoder() to specify one explicitly. If a default coder is registered, it may not be found due to type erasure; again, use setCoder() to specify a Coder explicitly.
        at com.google.cloud.dataflow.sdk.values.TypedPValue.inferCoderOrFail(TypedPValue.java:153)
        at com.google.cloud.dataflow.sdk.values.TypedPValue.getCoder(TypedPValue.java:44)
        at com.google.cloud.dataflow.sdk.values.PCollection.getCoder(PCollection.java:106)
        at com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner$Evaluator.ensurePCollectionEncodable(DirectPipelineRunner.java:808)
        at com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner$Evaluator.setPCollectionValuesWithMetadata(DirectPipelineRunner.java:735)
        at com.google.cloud.dataflow.sdk.transforms.ParDo.evaluateSingleHelper(ParDo.java:990)
        at com.google.cloud.dataflow.sdk.transforms.ParDo.access$100(ParDo.java:425)
        at com.google.cloud.dataflow.sdk.transforms.ParDo$1.evaluate(ParDo.java:972)
        at com.google.cloud.dataflow.sdk.transforms.ParDo$1.evaluate(ParDo.java:967)
        at com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner$Evaluator.visitTransform(DirectPipelineRunner.java:652)
        at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:200)
        at com.google.cloud.dataflow.sdk.runners.TransformTreeNode.visit(TransformTreeNode.java:196)
        at com.google.cloud.dataflow.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:109)
        at com.google.cloud.dataflow.sdk.Pipeline.traverseTopologically(Pipeline.java:204)
        at com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner$Evaluator.run(DirectPipelineRunner.java:609)
        at com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner.run(DirectPipelineRunner.java:335)
        at com.google.cloud.dataflow.sdk.runners.DirectPipelineRunner.run(DirectPipelineRunner.java:73)
        at com.google.cloud.dataflow.sdk.Pipeline.run(Pipeline.java:145)
        at com.google.cloud.genomics.dataflow.pipelines.CountReads.main(CountReads.java:146)
        at com.google.cloud.genomics.dataflow.pipelines.CountReadsITCase.testLocal(CountReadsITCase.java:58)
$
```

**Comment by jean-philippe-martin** [comment]
excellent, you were able to reproduce the error. That's what I'm seeing too.

**Comment by pgrosu** [comment]
Great, now we're starting from the same point :)  I'll keep looking into it.

**Comment by pgrosu** [comment]
I had a chance to work on this over the weekend, and I was inspecting the classes that got loaded during the `verify` step, and I think that might be one of the causes for the failures.  I was wondering if you could try the following update to `pom.xml`, which seems to fix some things with the failures - though I don't have a GCS account to fully test this:

Just add the following three lines [after line 290 in your pom.xml](https://github.com/googlegenomics/dataflow-java/blob/012854e76998e4d0cad957d7f1a6d9b36fb635ea/pom.xml#L290)

```
    <configuration>
        <useSystemClassLoader>false</useSystemClassLoader>
    </configuration>
```

The updated section should look like this:

```
   <!-- adds "mvn verify" command to run the integration tests (any test ending in IT or ITCase). -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>2.18.1</version>
        <configuration>
                  <useSystemClassLoader>false</useSystemClassLoader>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```		
		
Below is a link with more documentation regarding this:

http://maven.apache.org/surefire/maven-failsafe-plugin/examples/class-loading.html

Let me know if this fixes it.

Thanks,
~p

**Comment by jean-philippe-martin** [comment]
Wow, it looks like this fixes it! I was able to see all passing tests now.
Congratulations!
Sadly it doesn't fix my "mvn verify takes 7min" bug, but that's unrelated.
I'm pushing your change in a PR.

**Comment by pgrosu** [comment]
It's a team effort, and I'm always happy to help out :)  I will look into why it might take that long, but that could be due to other reasons in terms of infrastructure and what the tests are required to perform.

On another note, is it okay to comment/contribute to [hellbender](https://github.com/broadinstitute/hellbender)?  Some of the posts this morning led me there.

Thanks,
~p

**Comment by wbrockman** [comment]
Paul,
Not to speak for the organizers of the Hellbender project, but I know it is
in very early days and a lot is changing very quickly.  So it wouldn't be
high on my list of open-source projects to get involved with right now.
Will

**Comment by pgrosu** [comment]
Hi Will,

Thank you for the heads up.  Though I usually prefer early-stage projects more, I won't make it a high-priority, and will just contribute sporadically if I notice something that might be helpful in general or about Dataflow.  Actually I downloaded it, packaged and ran it yesterday.  It has some really nice features, and it looks fairly straightforward and fun to use.

Thanks,
Paul

**Pull request merged**
